// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: hello.proto

package proto

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SrvInterface service

func NewSrvInterfaceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SrvInterface service

type SrvInterfaceService interface {
	Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type srvInterfaceService struct {
	c    client.Client
	name string
}

func NewSrvInterfaceService(name string, c client.Client) SrvInterfaceService {
	return &srvInterfaceService{
		c:    c,
		name: name,
	}
}

func (c *srvInterfaceService) Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SrvInterface.Hello", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SrvInterface service

type SrvInterfaceHandler interface {
	Hello(context.Context, *Request, *Response) error
}

func RegisterSrvInterfaceHandler(s server.Server, hdlr SrvInterfaceHandler, opts ...server.HandlerOption) error {
	type srvInterface interface {
		Hello(ctx context.Context, in *Request, out *Response) error
	}
	type SrvInterface struct {
		srvInterface
	}
	h := &srvInterfaceHandler{hdlr}
	return s.Handle(s.NewHandler(&SrvInterface{h}, opts...))
}

type srvInterfaceHandler struct {
	SrvInterfaceHandler
}

func (h *srvInterfaceHandler) Hello(ctx context.Context, in *Request, out *Response) error {
	return h.SrvInterfaceHandler.Hello(ctx, in, out)
}
